config/routes.rb
Rails.application.routes.draw do
  resources :users, only: :show do
    scope module: :users do
      resource :follow,    only: :create
      resource :following, only: :show
      resource :followers, only: :show
    end
  end

  resources :relationships, only: %i[ new create ]
  resources :tweets,        only: %i[ index new create ]

  # Authentication
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get  "sign_in",  to: "sessions#new"
  post "sign_in",  to: "sessions#create"

  delete "sign_out", to: "sessions#destroy"

  # Username
  get '/:username', to: 'users#show', as: "username"

  # Root
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  scope :reverse_chronologically, -> { order created_at: :desc }
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user,   class_name: "User", foreign_key: "user_id",   counter_cache: :following_count
  belongs_to :target, class_name: "User", foreign_key: "target_id", counter_cache: :followers_count

  validates_uniqueness_of :user_id, scope: :target_id, message: "is already followed"
  validate :cannot_follow_yourself

  def cannot_follow_yourself
    errors.add(:base, "You cannot follow yourself") if user == target
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user, counter_cache: true

  delegate :name, :username, to: :user

  validates :message, presence: true, length: { maximum: 280 }
end

app/models/user.rb
class User < ApplicationRecord
  include Registrable, Relationshipable, Feedable
end

app/models/user/feedable.rb
module User::Feedable
  extend ActiveSupport::Concern

  included do
    has_many :tweets, dependent: :destroy

    delegate :size, prefix: true, to: :tweets
  end

  def feed
    Tweet.where(user: self).or(following_tweets)
  end

  private
    def following_tweets
      Tweet.where(user: following)
    end
end

app/models/user/registrable.rb
module User::Registrable
  extend ActiveSupport::Concern

  included do
    has_secure_password

    scope :alphabetically, -> { order :name }

    validates :email, format: { with: /\A[^@\s]+@[^@\s]+\z/ }

    validates :name,     presence: true
    validates :username, presence: true, uniqueness: { case_sensitive: false }
    validates :email,    presence: true, uniqueness: { case_sensitive: false }
  end

  def current?
    self == Current.user
  end  
end

app/models/user/relationshipable.rb
module User::Relationshipable
  extend ActiveSupport::Concern

  included do
    has_many :following_relationships, class_name: "Relationship", foreign_key: "user_id",   dependent: :destroy
    has_many :followers_relationships, class_name: "Relationship", foreign_key: "target_id", dependent: :destroy

    has_many :following, through: :following_relationships, source: :target, counter_cache: :following_count
    has_many :followers, through: :followers_relationships, source: :user,   counter_cache: :followers_count

    delegate :size, prefix: true, to: :following
    delegate :size, prefix: true, to: :followers
  end

  def following?
    following.exists?(Current.user.id)
  end

  def followed?
    followers.exists?(Current.user.id)
  end

  def follow
    followers_relationships.create!(user: Current.user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticate
end

app/controllers/concerns/authenticate.rb
module Authenticate
  extend ActiveSupport::Concern

  included do
    include BySession

    before_action :authenticate
  end

  private
    def authenticate
      if authenticate_with_session
        # Great! You're in
      elsif !performed?
        request_session_authentication
      end
    end

    def authenticated(user, by:)
      benchmark "#{authentication_identification(user)} by #{by}" do
        @authenticated_by     = by.to_s.inquiry
        @authenticated_user   = user

        Current.user = user
      end
    end

    def signed_in?
      @authenticated_user != nil
    end

    def authentication_identification(user)
      "Authorized #{user.username}"
    end
end

app/controllers/concerns/authenticate/by_session.rb
module Authenticate::BySession
  include ActiveSupport::SecurityUtils

  private
    def authenticate_with_session
      if user = User.find_by(id: session[:user_id])
        authenticated user, by: :session
      end
    end

    def request_session_authentication
      redirect_to sign_in_url
    end

    def sign_in(user)
      session[:user_id] = user.id; redirect_to root_url
    end

    def sign_out
      session[:user_id] = nil; redirect_to sign_in_url
    end
end

app/controllers/concerns/user_scoped.rb
module UserScoped
  extend ActiveSupport::Concern

  included do
    before_action :set_user
  end

  private
    def set_user
      @user = User.find(params[:user_id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :authenticate

  def new
    @user = User.new;
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user, only: :create

  def new
    @relationship = Relationship.new
  end

  def create
    @relationship = Relationship.new(user: Current.user, target: @user)
    if @relationship.save
      redirect_to @user, notice: "User was successfully followed"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def set_user
      if @user = User.find_by(username: params[:username])
        # Nice, I found this user!
      else
        redirect_to new_relationship_path, notice: "User not found!"
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: user_params[:username])
    if @user && @user.authenticate(user_params[:password])
      sign_in @user
    else
      redirect_to sign_in_url, flash: { username_hint: params[:user][:username], notice: "Username or password are wrong!" }
    end
  end

  def destroy
    sign_out
  end

  private
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    set_page_and_extract_portion_from Current.user.feed.reverse_chronologically, per_page: 10
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.build(tweet_params)
    @tweet.save!

    redirect_to tweets_path, notice: "Tweet was successfully created"
  end

  private
    def tweet_params
      params.require(:tweet).permit(:message)
    end
end

app/controllers/users/followers_controller.rb
class Users::FollowersController < ApplicationController
  include UserScoped

  def show
    set_page_and_extract_portion_from @user.followers.alphabetically, per_page: 10
  end
end

app/controllers/users/followings_controller.rb
class Users::FollowingsController < ApplicationController
  include UserScoped

  def show
    set_page_and_extract_portion_from @user.following.alphabetically, per_page: 10
  end
end

app/controllers/users/follows_controller.rb
class Users::FollowsController < ApplicationController
  include UserScoped

  def create
    @user.follow; redirect_to @user, notice: "You are now following #{@user.name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    set_page_and_extract_portion_from @user.tweets.reverse_chronologically, per_page: 10
  end

  private
    def set_user
      if params[:username]
        @user = User.find_by!(username: params[:username])
      else
        @user = User.find(params[:id])
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    content_for(:title) || "Twitter Clone"
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def tweet_header(tweet)
    sanitize "<strong>#{tweet.name}</strong>, #{at tweet.user} - #{l tweet.created_at, format: :long}"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def at(user)
    "@#{user.username}"
  end

  def format_user(user)
    "#{user.name} (#{at user})"
  end
end

app/views/tweets/_tweet.html.erb
<article class="push-sm--bottom">
  <header>
    <%= tweet_header tweet %>
  </header>
  <p><%= tweet.message %><p>
</article>

app/views/tweets/index.html.erb
<% content_for :title, "Home / Twitter Clone" %>

<main class="page__content">
  <header class="content-header">
    <h1 class="txt--xl flush">Home</h1>
  </header>

  <section class="content-body">
    <%= render @page.records %>
    <%= link_to "Next page", tweets_path(page: @page.next_param), class: "btn btn--secondary" unless @page.last? %>
  <section>
</main>

app/views/tweets/new.html.erb
<% content_for :title, "Home / Twitter Clone" %>

<main class="page__content">
  <header class="content-header">
    <h1 class="txt--xl flush">New Tweet</h1>
  </header>

  <section class="content-body">
    <%= form_with(model: @tweet) do |form| %>
      <%= form.text_area :message, class: "input", required: true, maxlength: 280, autofocus: true, placeholder: "What's happening?" %>
      <%= form.submit class: "btn btn--primary" %>
    <% end %>
  <section>
</main>

app/views/users/_user.html.erb
<article class="flex flex--items-center flex--justify-between push-lg--bottom">
  <%= link_to "#{user.name} #{at user}", user %>
  <%= link_to "Follow", [user, :follow], method: :post, class: "btn btn--secondary btn--small" unless user.followed? %>
</article>

app/views/users/followers/show.html.erb
<% content_for :title, "People following #{format_user(@user)} / Twitter Clone" %>

<main class="page__content">
  <header class="content-header">
    <div class="push-md--bottom">
      <h1 class="txt--xl flush"><%= @user.name %></h1>
      <div class="txt--sm"><%= at @user %></div>
    </div>

    <div>
      <h2 class="txt--lg flush">Followers</h2>
    </div>
  </header>

  <section class="content-body">
    <%= render partial: "/users/user", collection: @page.records %>
    <%= link_to "Next page", user_followers_path(@user, page: @page.next_param), class: "btn btn--secondary" unless @page.last? %>
  <section>
</main>

app/views/users/followings/show.html.erb
<% content_for :title, "People followed by #{format_user(@user)} / Twitter Clone" %>

<main class="page__content">
  <header class="content-header">
    <div class="push-md--bottom">
      <h1 class="txt--xl flush"><%= @user.name %></h1>
      <div class="txt--sm"><%= at @user %></div>
    </div>

    <div class="flex flex--items-center flex--justify-between">
      <h2 class="txt--lg flush">Following</h2>
      <%= link_to "Follow another user", new_relationship_path, class: "btn btn--secondary btn--small" %>
    </div>
  </header>

  <section class="content-body">
    <%= render partial: "/users/user", collection: @page.records %>
    <%= link_to "Next page", user_following_path(@user, page: @page.next_param), class: "btn btn--secondary" unless @page.last? %>
  <section>
</main>

app/views/users/show.html.erb
<% content_for :title, "#{format_user(@user)} / Twitter Clone" %>

<main class="page__content">
  <header class="content-header">
    <h1 class="txt--xl flush"><%= @user.name %></h1>
    <div class="txt--sm"><%= @user.tweets_size %> Tweets</div>
  </header>

  <section class="content-body">
    <ul class="list--inline unpad">
      <li><%= link_to "#{@user.following_size} Following", [@user, :following] %></li>
      <li><%= link_to "#{@user.followers_size} Followers", [@user, :followers] %></li>
      <li><%= link_to "Follow", [@user, :follow], method: :post, class: "btn btn--secondary btn--small" unless (@user.followed? || @user.current?) %></li>
    </ul>

    <%= render @page.records %>
    <%= link_to "Next page", user_path(@user, page: @page.next_param), class: "btn btn--secondary" unless @page.last? %>
  <section>
</main>